1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [12]:
#importing all required libraries
import requests
import time
from selenium.webdriver.common.by import By
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementNotVisibleException, ElementNotInteractableException, ElementClickInterceptedException 

import warnings
warnings.filterwarnings("ignore")

page = requests.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
soup = BeautifulSoup(page.content)

#connecting to the web driver
driver = webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

driver.find_element(By.XPATH, "//b").click() 

#creating empty list 
records = []

for row in driver.find_elements_by_xpath("(//table[@class='wikitable sortable jquery-tablesorter'])[1]//tr")[1:-1]:
    temp = ''
    for element in row.find_elements_by_xpath(".//td"):        
        temp += element.text + '|'
    records.append(temp.split('|')[:-2])

    
data = pd.DataFrame(records, columns=['Rank', 'Video_Name', 'Artist', 'Views', 'Date_of_upload'])
data.Video_Name = data.Video_Name.apply(lambda x:x[:-4].strip('"'))
data

,Rank,Video_Name,Artist,Views,Date_of_upload
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,11.09,"June 17, 2016"
1,2.,Despacito,Luis Fonsi,7.94,"January 12, 2017"
2,3.,Johny Johny Yes Papa,LooLoo Kids,6.41,"October 8, 2016"
3,4.,Shape of You,Ed Sheeran,5.78,"January 30, 2017"
4,5.,See You Again,Wiz Khalifa,5.59,"April 6, 2015"
5,6.,Bath Song,Cocomelon – Nursery Rhymes,5.55,"May 2, 2018"
6,7.,Phonics Song with Two Words,ChuChu TV,4.79,"March 6, 2014"
7,8.,Uptown Funk,Mark Ronson,4.65,"November 19, 2014"
8,9.,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,4.60,"February 27, 2018"
9,10.,Gangnam Style,Psy,4.51,"July 15, 2012"
10,11.,Masha and the Bear – Recipe for Disaster,Get Movies,4.50,"January 31, 2012"
11,12.,Wheels on the Bus,Cocomelon – Nursery Rhymes,4.25,"May 24, 2018"
12,13.,Dame Tu Cosita,El Chombo,4.01,"April 5, 2018"
13,14.,Sugar,Maroon 5,3.74,"January 14, 2015"
14,15.,Roar,Katy Perry,3.63,"September 5, 2013"
15,16.,Counting Stars,OneRepublic,3.62,"May 31, 2013"
16,17.,Sorry,Justin Bieber,3.57,"October 22, 2015"
17,18.,Thinking Out Loud,Ed Sheeran,3.48,"October 7, 2014"
18,19.,Axel F,Crazy Frog,3.46,"June 16, 2009"
19,20.,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,3.32,"June 25, 2018"
20,21.,Dark Horse,Katy Perry,3.32,"February 20, 2014"
21,22.,Faded,Alan Walker,3.32,"December 3, 2015"
22,23.,Girls Like You,Maroon 5,3.32,"May 31, 2018"
23,24.,Let Her Go,Passenger,3.27,"July 25, 2012"
24,25.,Bailando,Enrique Iglesias,3.25,"April 11, 2014"
25,26.,Lean On,Major Lazer,3.24,"March 22, 2015"
26,27.,Perfect,Ed Sheeran,3.22,"November 9, 2017"
27,28.,Waka Waka (This Time for Africa),Shakira,3.21,"June 4, 2010"
28,29.,Shake It Off,Taylor Swift,3.19,"August 18, 2014"
29,30.,Mi Gente,J Balvin,3.12,"June 29, 2017"

2.Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [96]:
#importing all required libraries
import requests
import time
from selenium.webdriver.common.by import By
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementNotVisibleException, ElementNotInteractableException, ElementClickInterceptedException 


page = requests.get("https://www.bcci.tv/")
soup = BeautifulSoup(page.content)

#connectiong to webdriver
driver = webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')
driver.get("https://www.bcci.tv/")
driver.maximize_window()


#going to international fixtures page
fixtures=driver.find_element_by_xpath('/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
try:
    fixtures.click()
except ElementNotInteractableException:
    driver.get(fixtures.get_attribute('href'))
    
time.sleep(5)

# creating empty lists for scraping the data
Match_Title = []
Series = []
Place = []
Date = []
Time = []

for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__format']"):
    Match_Title.append(i.text)

time.sleep(5)

for i in driver.find_elements_by_xpath("//div[@class='fixture__format-strip']/span[@class='u-unskewed-text fixture__tournament-label u-truncated']"):
    Series.append(i.text)
time.sleep(5)

for i in driver.find_elements_by_xpath("//div[@class='fixture__description u-unskewed-text']/p/span"):
    Place.append(i.text)
time.sleep(5)

for i in driver.find_elements_by_xpath("//span[@class='fixture__datetime tablet-only']/strong[1]"):
    Date.append(i.text.replace('\n',' '))

date=[i.split(' ',3)[:3] for i in Date]
date=[' '.join(i) for i in date]
Time=[i.split(' ',3)[-1] for i in Date]

# creating data frame
fixture=pd.DataFrame({'Match_Title': Match_Title,
                          "Series": Series,
                          "Place": Place,
                          "Date": date,
                          "Time": Time})
fixture

Empty DataFrame
Columns: [Match_Title, Series, Place, Date, Time]
Index: []

3.Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [29]:
#importing all required libraries
import requests
import time
from selenium.webdriver.common.by import By
import requests
from bs4 import BeautifulSoup
import selenium
from selenium import webdriver
import pandas as pd
import time
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException, ElementNotVisibleException, ElementNotInteractableException, ElementClickInterceptedException 

import warnings
warnings.filterwarnings("ignore")

page = requests.get("https://www.guru99.com/")
soup = BeautifulSoup(page.content)

#connecting to the web driver
driver = webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')
driver.get("https://www.guru99.com/")
driver.maximize_window()

error = driver.find_element_by_xpath('//*[@id="java_technologies"]/li[3]/a').get_attribute('href')
driver.get(error)
time.sleep(3)
exception = driver.find_element_by_xpath('/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a').get_attribute('href')
driver.get(exception)

Data = []
table = driver.find_elements_by_xpath("//table[@class='table table-striped']//td")
for i in table:
    try:
        Data.append(i.text)
    except NoSuchElementException:
        Data.append('-')

Name = []
for i in range(2,len(Data),2):
    Name.append(Data[i])

Description = []
for i in range(3,len(Data),2):
    Description.append(Data[i])

df=pd.DataFrame({"Exception name": Name, "Exception description": Description})
df

,Exception name,Exception description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

4.Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [124]:
# connecting to the web driver
driver=webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')

driver.get("https://statisticstimes.com/")
# clicking on Economy button
driver.find_element_by_xpath("//div[@class='navbar']/div[2]/button").click()
time.sleep(5)

# clicking on India
driver.find_element_by_xpath("//div[@class='dropdown-content']/a[3]").click()
time.sleep(5)

# clicking on GDP of Indian Economy
GDP = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/ul/li[1]/a").click()
time.sleep(5)

# creating empty list
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDP_billion = []

# scraping Rank
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# scraping State
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
    
# scraping GSDP at current price (17-18)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException:
    GSDP1.append("_")
# scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
    
# scraping Share (18-19)
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
    
# scraping GDP $ billion
try:
    for i in driver.find_elements_by_xpath("//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("_")
    
    
# creating DataFrame from the scraped data
GDP = pd.DataFrame({})
GDP['Rank'] = Rank
GDP['State'] = State
GDP['GSDP at current price (18-19)'] = GSDP1
GDP['GSDP at current price (17-18)'] = GSDP2
GDP['Share (18-19)'] = Share
GDP['GDP($ billion)'] = GDP_billion
GDP

,Rank,State,GSDP at current price (18-19),GSDP at current price (17-18),Share (18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
61,29,Sikkim,"28,391","25,141",0.15%,"17,060"
62,30,Nagaland,-,"24,534",0.15%,-
63,31,Arunachal Pradesh,-,"22,488",0.13%,-
64,32,Mizoram,"24,424","20,947",0.13%,"17,797"
65,33,Andaman & Nicobar Islands,-,-,-,-

5.Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [98]:
url = "https://github.com/"
page = requests.get(url)

soup = BeautifulSoup(page.content)

driver = webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')
driver.get(url)
driver.maximize_window()

# clicking on option button
explore_btn=driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/summary")
explore_btn.click()
time.sleep(2)

#finding trending option
trending=driver.find_element_by_xpath('/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a')
try:
    explore.click()
except:
    driver.get(explore_btn.get_attribute('href'))
time.sleep(2)

# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repo=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']/a")
for i in repo:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2)    
    
#scraping repositories title
repo_title=[]
try:
    repo=driver.find_elements_by_xpath("//h1[@class='h3 lh-condensed']")
    for i in repo:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
     #scraping repositories discription
    try:          
        repo_desc.append(driver.find_element_by_xpath("//p[@class='f4 mt-3']").text)
    except:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element_by_xpath("//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements_by_xpath("//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,pacocoursey / cmdk,-,6,"[TypeScript, SCSS]"
1,TheAlgorithms / Python,-,826,[Python]
2,InterviewReady / system-design-resources,-,5,[No languages used]
3,Alcibiades-Capital / mev_bundle_generator,-,No details available,"[Rust, Solidity]"
4,craftzdog / dotfiles-public,-,7,"[Lua, Shell, PowerShell]"
5,hasura / graphql-engine,-,454,"[Haskell, TypeScript, JavaScript, Go, Python, ..."
6,eugeneyan / applied-ml,-,38,[No languages used]
7,MatrixTM / MHDDoS,-,26,"[Python, Dockerfile]"
8,onekey-sec / unblob,-,10,"[Python, Nix]"
9,rad9800 / TamperingSyscalls,-,2,"[C++, Python]"
10,jwasham / coding-interview-university,-,256,[No languages used]
11,toeverything / AFFiNE,-,16,"[TypeScript, JavaScript, CSS, HTML, Shell, SCSS]"
12,Baiyuetribe / paper2gui,-,No details available,[Jupyter Notebook]
13,Asabeneh / 30-Days-Of-React,-,8,"[JavaScript, HTML]"
14,duckdb / duckdb,-,143,"[C++, C, Python, JavaScript, Julia, Java]"
15,RalfJung / minirust,-,5,[No languages used]
16,datahub-project / datahub,-,259,"[Java, Python, TypeScript, JavaScript, Shell, ..."
17,microsoft / qlib,-,97,"[Python, Cython]"
18,labmlai / annotated_deep_learning_paper_implem...,-,13,"[Jupyter Notebook, Python]"
19,iptv-org / iptv,-,182,"[JavaScript, Shell]"
20,leochen-g / wechat-assistant-pro,-,No details available,"[JavaScript, Dockerfile]"
21,openairplay / airplay2-receiver,-,13,[Python]
22,Developer-Y / cs-video-courses,-,69,[No languages used]
23,withastro / astro,-,298,"[TypeScript, JavaScript, Astro, Vue, Svelte, CSS]"
24,gofiber / fiber,-,236,[Go]

6.Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [113]:
# Activating the chrome browser
driver=webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')
time.sleep(5)

# Opening the billboard
url = "https://www.billboard.com/"
driver.get(url)
time.sleep(5)


#clicking the hot 100 songs link
charts=driver.find_element_by_xpath('/html/body/div[3]/header/div[1]/div/div/div[2]/div/nav/ul/li[1]')
try:
    charts.click()
except ElementNotInteractableException:
    driver.get(charts.get_attribute('href'))
time.sleep(5)


#scraping song names
song_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']")
    for i in names:
        song_name.append(i.text)
except NoSuchElementException:       #handling no such element exception
    song_name.append('No details available')
time.sleep(5)    


#scraping artist_names 
artist_name=[]
try:
    names=driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']")
    for i in names:
        artist_name.append(i.text)
except NoSuchElementException:        #handling no such element exception
    artist_name.append('No details available')
time.sleep(5)
    

#scraping last week rank
last_week_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']")
    for i in ranks:
        last_week_rank.append(i.text)
except NoSuchElementException:        #handling no such element exception
    last_week_rank.append('No details available') 
time.sleep(5)

#scraping peak rank
peak_rank=[]
try:
    ranks=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']")
    for i in ranks:
        peak_rank.append(i.text)
except NoSuchElementException:      #handling no such element exception
    peak_rank.append('No details available')
time.sleep(5)

#scraping weeks on chart
weeks=[]
try:
    week_count=driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']")
    for i in week_count:
        weeks.append(i.text)
except NoSuchElementException:          #handling no such element exception
    weeks.append('No details available')
time.sleep(5)


#creating dataframe
df=pd.DataFrame({'Song_Name':song_name,
                'Artist_Name':artist_name,
                'Last_week_rank':last_week_rank,
                'Peak':peak_rank,
                'Weeks_on_chart':weeks})
df

Empty DataFrame
Columns: [Song_Name, Artist_Name, Last_week_rank, Peak, Weeks_on_chart]
Index: []

7.Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/hr-recruiters-consultants
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [117]:
# connecting to the web driver
driver=webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')

# getting the webpage of mentioned url
url = ('https://www.naukri.com/hr-recruiters-consultants')
driver.get(url)
time.sleep(3)

# navigating to the recruiter page
recruiters = driver.find_element_by_xpath("//a[@title='Search Recruiters']")
page_url = recruiters.get_attribute("href")

driver.get(page_url)
time.sleep(3)
# fetching search button, sending keys and clicking on it
search = driver.find_element_by_xpath("//div[@class='inpWrap']//input")
search.send_keys("Data Science")

btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()
time.sleep(3)

# creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

# scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)


# scraping data of Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    Designation.append(i.text)
time.sleep(3)


# scraping data of Company Name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)
time.sleep(3)


# scraping data of Skills
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
time.sleep(3)

# scraping data of Location
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/span/small"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Location.append(i.text)
    except NoSuchElementException:
        Location.append('-')
time.sleep(3)


# converting the scrapped data into a dataframe
Naukri = pd.DataFrame({})
Naukri['Name'] = Name[:48]
Naukri['Designation'] = Designation[:48]
Naukri['Company'] = Company[:48]
Naukri['Skills'] = Skills[:48]
Naukri['Location'] = Location[:48]
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Delhi
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Mysoru / Mysore
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Hyderabad / Secunderabad
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Bengaluru / Bangalore
34,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",New Delhi
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Chennai
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Aligarh
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Salt Lake City
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Pune
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Mumbai
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Indore
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Bengaluru / Bangalore
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",MYSORE
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Hyderabad / Secunderabad
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Bengaluru / Bangalore
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Mumbai
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Ghaziabad

8.Scrape the details of Highest selling novels.
URL = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [90]:
# connecting to the web driver
driver=webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')

# getting the webpage of mentioned url
url = ("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")
driver.get(url)
time.sleep(3)
# creating empty lists
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []


# scraping book names data
for i in driver.find_elements_by_xpath("//tbody//tr//td[2]"):
    Book_name.append(i.text)

    
# scraping author names data
for i in driver.find_elements_by_xpath("//tbody//tr//td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author_name.append(i.text)
    except NoSuchElementException:
        Author_name.append('-')
time.sleep(3)


# scraping data of volumes sold
for i in driver.find_elements_by_xpath("//tbody//tr//td[4]"):
    Volumes_sold.append(i.text)
    
    
# scraping data of publisher names
for i in driver.find_elements_by_xpath("//tbody//tr//td[5]"):
    Publisher.append(i.text)

# scraping  data of genre
for i in driver.find_elements_by_xpath("//tbody//tr//td[6]"):
    Genre.append(i.text)    
    
    
# creating dataframe for scraped data
Novels = pd.DataFrame({})
Novels['Book Name'] = Book_name
Novels['Author'] = Author_name
Novels['Volume sold'] = Volumes_sold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9.Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [91]:
driver=webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')

# getting the webpage of mentioned url
url = ("https://www.imdb.com/list/ls095964455/")
driver.get(url)
# creating empty lists
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

# scraped data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
    
# scraped data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
    
# scraped data of Genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)
    
    
# scraped data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)

# scraped data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
    
# scraped data of Votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text) 
    
    
# creating dataframe for scraped data
TV_Series = pd.DataFrame({})
TV_Series['Name'] = Name
TV_Series['Year Span'] = Year_span
TV_Series['Genre'] = Genre
TV_Series['Run Time'] = Run_time
TV_Series['Ratings'] = Ratings
TV_Series['Votes'] = Votes
TV_Series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,021,662"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,118,305"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"959,888"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"286,957"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"246,556"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,269"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,169"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"193,425"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,808"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"233,417"

10.Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [95]:
url = "https://archive.ics.uci.edu/"
page = requests.get(url)
soup = BeautifulSoup(page.content)

driver = webdriver.Chrome(r'C:\Users\sanka\Downloads\Compressed\chromedriver_win32_2\chromedriver.exe')
driver.get(url)
driver.maximize_window()

respository=driver.find_element_by_xpath("//span[@class='normal']/b/a")
respository.click()
    
Name=[]
Type=[]
Task=[]
Attribute=[]
No_of_Instance=[]
No_of_Attribute=[]
Year=[]

# Scrapping data for dataset name
try:
    names=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')
    
# Scrapping data for data type
try:
    types=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in types[1:]:
        Type.append(i.text)
except NoSuchElementException:
    Type.append('-')

# Scrapping data for default task
try:
    task=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in task[1:]:
        Task.append(i.text)
except NoSuchElementException:
    Task.append('-')
        
# Scrapping data for attribute type
try:
    attribute=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attribute[1:]:
        Attribute.append(i.text)
except NoSuchElementException:
    Attribute.append('-')
       
# Scrapping data for number of instances
try:
    instance=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in instance[1:]:
        No_of_Instance.append(i.text)
except NoSuchElementException:
    No_of_Instance.append('-')
        
# Scrapping data for number of attributes
try:
    attribute_no=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in attribute_no[1:]:
        No_of_Attribute.append(i.text)
except NoSuchElementException:
    No_of_Attribute.append('-')
        
# Scrapping data for the year details
try:
    year=driver.find_elements_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in year[1:]:
        Year.append(i.text)
except NoSuchElementException:
    Year.append('-')
    
# Creating the dataframe
df=pd.DataFrame({"Dataset Name":Name, "Data Type":Type, "Default Task":Task, "Attribute Type":Attribute, 
                 "No of instances":No_of_Instance, "No of atrributes":No_of_Attribute, "Year":Year})
df

,Dataset Name,Data Type,Default Task,Attribute Type,No of instances,No of atrributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021